### ISSUE TITLE
Implement concurrency to monitor multiple products/websites 

### ISSUE THREAD

**Issue by jamierajewski** [jamierajewski/ps5-bot#3]
Self-explanatory. This may require moving from selenium to something more custom built with an HTTP library and an HTML parser. At that point, it might be worth exploring other tools like Go which could make this easier.

**Comment by bgreni** [comment]
Maybe we could just spawn a bunch of processes for each product/site combination? 

https://docs.python.org/3/library/multiprocessing.html

**Comment by jamierajewski** [comment]
I thought about that, but since it's launching a whole browser per instance that would probably get slow pretty quick depending on the machine. I'm not sure how much better it would be once it's run in headless mode, but I think doing basic requests and parsing the result would likely be more resource-efficient. It's worth a shot though at least just to benchmark it
